apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-helloworld
  namespace: production
  labels:
    app: k8s-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-helloworld
  template:
    metadata:
      labels:
        app: k8s-helloworld
    spec:
      containers:
      - name: k8s-helloworld
        image: mikelarson123/k8s_helloworld:4
        ports:
        - containerPort: 80
        env:
        - name: NAME
          value: mikkel
